### PR TITLE
fix(readme): standardize format + link to docs

### PR DESCRIPTION
**Pull request by ami**

### CODE REVIEW

**Comment by pon** [comment]
LGTM

**Comment by leore** [comment]
needs a rebase so builds can pass.

**Comment by mgartner** [comment]
@ami since this is your own fork I can't rebase and push it for you. Ping me tomorrow and I can hep you do this so we can get this merged.

**Comment by ami** [comment]
closed in favor of https://github.com/lob/lob-php/pull/39

**Pull request closed without merging**
